spring:
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite::resource:test.db
    schema:
      - classpath:schema.sql # 建表语句
    data:
      - classpath:data.sql # 数据插入语句
    initialization-mode: always # 始终初始化
    continue-on-error: true # 初始化语句执行失败时继续启动应用

logging:
  level:
    byx:
      test: debug
